openapi: 3.0.0
info:
  title: Order Management API
  version: 1.0.0
servers:
  - url: http://localhost:8000/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        token_type:
          type: string
          example: Bearer
security:
  - bearerAuth: []
paths:
  /auth/register:
    post:
      summary: Register admin user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: test@example.com
                password:
                  type: string
                  example: mypassword123
      responses:
        '201':
          description: User created

  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: test@example.com
                password:
                  type: string
                  example: mypassword123
      responses:
        '200':
          description: JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /customers:
    get:
      summary: List customers
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of customers
    post:
      summary: Create customer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - phone
                - address
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  format: email
                  example: john@example.com
                phone:
                  type: string
                  example: "+254700000000"
                address:
                  type: string
                  example: Nairobi, Kenya
      responses:
        '201':
          description: Customer created

  /customers/{id}:
    get:
      summary: Get customer
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the customer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer details
    put:
      summary: Update customer
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the customer
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                address:
                  type: string
      responses:
        '200':
          description: Customer updated
    delete:
      summary: Delete customer
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the customer
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Customer deleted

  /orders:
    get:
      summary: List orders
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Page number (default 1)
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of orders per page (default 10)
          required: false
          schema:
            type: integer
            default: 10
        - name: status
          in: query
          description: Filter orders by status
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                  limit:
                    type: integer
                  total:
                    type: integer
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        customerId:
                          type: string
                        total:
                          type: number
                        status:
                          type: string
                        metadata:
                          type: object
                          additionalProperties: true
                        customer:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            email:
                              type: string
                            phone:
                              type: string
                            address:
                              type: string
    post:
      summary: Create order
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - customerId
                - total
              properties:
                customerId:
                  type: string
                  description: ID of the customer
                  example: "1234"
                total:
                  type: number
                  description: Total amount of the order
                  example: 2500.5
                status:
                  type: string
                  description: Status of the order (default: pending)
                  example: pending
                metadata:
                  type: object
                  description: Optional extra data
                  additionalProperties: true
                  example:
                    notes: "Deliver before 5pm"
      responses:
        '201':
          description: Order created

  /orders/{id}:
    get:
      summary: Get order
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the order
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
    put:
      summary: Update order
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the order
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                  description: Updated customer ID
                  example: "1234"
                total:
                  type: number
                  description: Updated total amount
                  example: 3000.0
                status:
                  type: string
                  description: Updated order status
                  example: completed
                metadata:
                  type: object
                  description: Optional metadata
                  additionalProperties: true
                  example:
                    notes: "Customer requested gift wrap"
      responses:
        '200':
          description: Order updated
    delete:
      summary: Delete order
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the order
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Order deleted
